/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as factories from './factories'
export { ProposalState__factory } from './factories/ProposalState__factory'
export type { ProposalState } from './ProposalState'
