/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProposalState } from "./ProposalState";
export * as factories from "./factories";
export { ProposalState__factory } from "./factories/ProposalState__factory";
