/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EncodedWhitelistData,
  EncodedWhitelistDataInterface,
} from "../EncodedWhitelistData";

const _abi = [
  {
    type: "tuple",
    components: [
      {
        name: "selector",
        type: "uint256",
      },
      {
        name: "nationalities",
        type: "uint256[]",
      },
      {
        name: "identityCreationTimestampUpperBound",
        type: "uint256",
      },
      {
        name: "identityCounterUpperBound",
        type: "uint256",
      },
      {
        name: "sex",
        type: "uint256",
      },
      {
        name: "birthDateLowerbound",
        type: "uint256",
      },
      {
        name: "birthDateUpperbound",
        type: "uint256",
      },
      {
        name: "expirationDateLowerBound",
        type: "uint256",
      },
    ],
  },
] as const;

export class EncodedWhitelistData__factory {
  static readonly abi = _abi;
  static createInterface(): EncodedWhitelistDataInterface {
    return new Interface(_abi) as EncodedWhitelistDataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EncodedWhitelistData {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as EncodedWhitelistData;
  }
}
